from django.core.management.base import BaseCommand
from FO_game.models import HeroBase


class Command(BaseCommand):
    help = "Seed ALL hero base data (extend this file as needed)"

    def handle(self, *args, **options):
        data = [
            # =========================
            # UNDEAD – COMMONS
            # =========================
            {
                "name": "Bone Scavenger",
                "rarity": "Common",
                "element": "Void",
                "faction": "Undead",
                "role": "Frontline",
                "description": "A durable skeletal warrior constructed from battlefield remains.",
                "base_hp": 1400,
                "base_atk": 95,
                "base_def": 70,
                "base_matk": 20,
                "base_mdef": 40,
                "base_speed": 95,
                "growth_hp": 115,
                "growth_atk": 7,
                "growth_def": 6,
                "growth_matk": 1,
                "growth_mdef": 3,
                "growth_speed": 2,
            },
            {
                "name": "Rotting Ghoul",
                "rarity": "Common",
                "element": "Force",
                "faction": "Undead",
                "role": "Frontline",
                "description": "A ravenous corpse that relies on raw vitality over protection.",
                "base_hp": 1600,
                "base_atk": 110,
                "base_def": 30,
                "base_matk": 10,
                "base_mdef": 30,
                "base_speed": 100,
                "growth_hp": 140,
                "growth_atk": 9,
                "growth_def": 2,
                "growth_matk": 1,
                "growth_mdef": 2,
                "growth_speed": 3,
            },
            {
                "name": "Skeleton Archer",
                "rarity": "Common",
                "element": "Spirit",
                "faction": "Undead",
                "role": "Backline",
                "description": "Risen marksman providing ranged physical support.",
                "base_hp": 900,
                "base_atk": 120,
                "base_def": 40,
                "base_matk": 20,
                "base_mdef": 40,
                "base_speed": 105,
                "growth_hp": 70,
                "growth_atk": 10,
                "growth_def": 3,
                "growth_matk": 1,
                "growth_mdef": 3,
                "growth_speed": 4,
            },
            {
                "name": "Necro-Apprentice",
                "rarity": "Common",
                "element": "Magic",
                "faction": "Undead",
                "role": "Backline",
                "description": "An acolyte of death magic, blasting foes with necrotic energy.",
                "base_hp": 850,
                "base_atk": 30,
                "base_def": 30,
                "base_matk": 115,
                "base_mdef": 70,
                "base_speed": 95,
                "growth_hp": 65,
                "growth_atk": 2,
                "growth_def": 2,
                "growth_matk": 10,
                "growth_mdef": 5,
                "growth_speed": 2,
            },
            {
                "name": "Cursed Wisp",
                "rarity": "Common",
                "element": "Spirit",
                "faction": "Undead",
                "role": "Backline",
                "description": "A fast, ethereal spirit that harasses enemies from afar.",
                "base_hp": 700,
                "base_atk": 20,
                "base_def": 20,
                "base_matk": 100,
                "base_mdef": 90,
                "base_speed": 115,
                "growth_hp": 55,
                "growth_atk": 1,
                "growth_def": 1,
                "growth_matk": 8,
                "growth_mdef": 6,
                "growth_speed": 5,
            },

            # =========================
            # UNDEAD – UNCOMMONS (EXAMPLE)
            # =========================
            {
                "name": "Bone Drummer",
                "rarity": "Uncommon",
                "element": "Spirit",
                "faction": "Undead",
                "role": "Backline",
                "description": "Keeps the dead in rhythm, bolstering undead squads through relentless ritual.",
                "base_hp": 950,
                "base_atk": 35,
                "base_def": 35,
                "base_matk": 80,
                "base_mdef": 85,
                "base_speed": 100,
                "growth_hp": 75,
                "growth_atk": 2,
                "growth_def": 3,
                "growth_matk": 6,
                "growth_mdef": 6,
                "growth_speed": 3,
            },
            {
                "name": "Grave Watcher",
                "rarity": "Uncommon",
                "element": "Void",
                "faction": "Undead",
                "role": "Frontline",
                "description": "A sentinel that punishes enemies for attacking the dead.",
                "base_hp": 1750,
                "base_atk": 85,
                "base_def": 55,
                "base_matk": 25,
                "base_mdef": 65,
                "base_speed": 85,
                "growth_hp": 150,
                "growth_atk": 6,
                "growth_def": 4,
                "growth_matk": 2,
                "growth_mdef": 6,
                "growth_speed": 1,
            },
            {
                "name": "Corpse Stitcher",
                "rarity": "Uncommon",
                "element": "Magic",
                "faction": "Undead",
                "role": "Backline",
                "description": "Crudely reassembles undead mid-fight with serrated tools and dark magic.",
                "base_hp": 900,
                "base_atk": 25,
                "base_def": 30,
                "base_matk": 140,
                "base_mdef": 80,
                "base_speed": 90,
                "growth_hp": 70,
                "growth_atk": 1,
                "growth_def": 2,
                "growth_matk": 12,
                "growth_mdef": 5,
                "growth_speed": 2,
            },

            # =========================
            # UNDEAD – RARES / EPICS / LEGENDARY (EXAMPLES)
            # =========================
            {
                "name": "Bone Marshal",
                "rarity": "Rare",
                "element": "Void",
                "faction": "Undead",
                "role": "Frontline",
                "description": "A disciplined commander who binds lesser undead into an unyielding formation.",
                "base_hp": 1800,
                "base_atk": 105,
                "base_def": 85,
                "base_matk": 30,
                "base_mdef": 70,
                "base_speed": 90,
                "growth_hp": 135,
                "growth_atk": 8,
                "growth_def": 7,
                "growth_matk": 2,
                "growth_mdef": 5,
                "growth_speed": 2,
            },
            {
                "name": "Grave Binder",
                "rarity": "Rare",
                "element": "Magic",
                "faction": "Undead",
                "role": "Backline",
                "description": "A master of funerary rites who draws power from the dead left in his wake.",
                "base_hp": 1000,
                "base_atk": 35,
                "base_def": 35,
                "base_matk": 155,
                "base_mdef": 95,
                "base_speed": 95,
                "growth_hp": 80,
                "growth_atk": 2,
                "growth_def": 2,
                "growth_matk": 14,
                "growth_mdef": 7,
                "growth_speed": 2,
            },
            {
                "name": "Grave Marshal",
                "rarity": "Epic",
                "element": "Void",
                "faction": "Undead",
                "role": "Frontline",
                "description": "A master of undead warfare whose presence expands the limits of the battlefield itself.",
                "base_hp": 2200,
                "base_atk": 115,
                "base_def": 105,
                "base_matk": 35,
                "base_mdef": 90,
                "base_speed": 85,
                "growth_hp": 160,
                "growth_atk": 9,
                "growth_def": 9,
                "growth_matk": 2,
                "growth_mdef": 7,
                "growth_speed": 2,
            },
            {
                "name": "Lich Conductor",
                "rarity": "Epic",
                "element": "Magic",
                "faction": "Undead",
                "role": "Backline",
                "description": "An immortal maestro who accelerates the dead through the cadence of extinction.",
                "base_hp": 1100,
                "base_atk": 40,
                "base_def": 40,
                "base_matk": 185,
                "base_mdef": 115,
                "base_speed": 95,
                "growth_hp": 85,
                "growth_atk": 2,
                "growth_def": 3,
                "growth_matk": 16,
                "growth_mdef": 8,
                "growth_speed": 3,
            },
            {
                "name": "The Undying Sovereign",
                "rarity": "Legendary",
                "element": "Void",
                "faction": "Undead",
                "role": "Frontline",
                "description": "An eternal ruler whose dominion ensures that death itself is only a transition.",
                "base_hp": 2600,
                "base_atk": 140,
                "base_def": 120,
                "base_matk": 60,
                "base_mdef": 120,
                "base_speed": 80,
                "growth_hp": 180,
                "growth_atk": 10,
                "growth_def": 10,
                "growth_matk": 4,
                "growth_mdef": 9,
                "growth_speed": 2,
            },

            # =========================
            # GOBLIN – COMMONS
            # =========================
            {
                "name": "Goblin Cutthroat",
                "rarity": "Common",
                "element": "Force",
                "faction": "Goblin",
                "role": "Frontline",
                "description": "A reckless knife-fighter who relies on speed and numbers to overwhelm foes.",
                "base_hp": 950,
                "base_atk": 115,
                "base_def": 35,
                "base_matk": 20,
                "base_mdef": 30,
                "base_speed": 120,
                "growth_hp": 70,
                "growth_atk": 9,
                "growth_def": 2,
                "growth_matk": 1,
                "growth_mdef": 2,
                "growth_speed": 5,
            },
            {
                "name": "Goblin Spear Sneak",
                "rarity": "Common",
                "element": "Force",
                "faction": "Goblin",
                "role": "Frontline",
                "description": "A longer reach lets this goblin strike while hiding behind allies.",
                "base_hp": 1050,
                "base_atk": 105,
                "base_def": 45,
                "base_matk": 20,
                "base_mdef": 35,
                "base_speed": 115,
                "growth_hp": 85,
                "growth_atk": 8,
                "growth_def": 3,
                "growth_matk": 1,
                "growth_mdef": 2,
                "growth_speed": 4,
            },
            {
                "name": "Goblin Sling Bomber",
                "rarity": "Common",
                "element": "Fire",
                "faction": "Goblin",
                "role": "Backline",
                "description": "A goblin bombardier hurling volatile scrap from the safety of the backline.",
                "base_hp": 850,
                "base_atk": 125,
                "base_def": 30,
                "base_matk": 25,
                "base_mdef": 35,
                "base_speed": 110,
                "growth_hp": 65,
                "growth_atk": 10,
                "growth_def": 2,
                "growth_matk": 1,
                "growth_mdef": 2,
                "growth_speed": 4,
            },
            {
                "name": "Goblin Hex-Squeaker",
                "rarity": "Common",
                "element": "Magic",
                "faction": "Goblin",
                "role": "Backline",
                "description": "A shrill-voiced goblin whose petty hexes add up through sheer repetition.",
                "base_hp": 800,
                "base_atk": 25,
                "base_def": 25,
                "base_matk": 105,
                "base_mdef": 55,
                "base_speed": 120,
                "growth_hp": 60,
                "growth_atk": 1,
                "growth_def": 1,
                "growth_matk": 8,
                "growth_mdef": 4,
                "growth_speed": 5,
            },
            {
                "name": "Goblin Tinker",
                "rarity": "Common",
                "element": "Tech",
                "faction": "Goblin",
                "role": "Backline",
                "description": "A schemer who boosts goblin squads through crude contraptions and bad ideas.",
                "base_hp": 900,
                "base_atk": 35,
                "base_def": 35,
                "base_matk": 75,
                "base_mdef": 65,
                "base_speed": 105,
                "growth_hp": 70,
                "growth_atk": 2,
                "growth_def": 2,
                "growth_matk": 6,
                "growth_mdef": 4,
                "growth_speed": 3,
            },

            # =========================
            # GOBLIN – UNCOMMONS / RARES / EPICS / LEGENDARY (EXAMPLES)
            # =========================
            {
                "name": "Goblin Banner Scrapper",
                "rarity": "Uncommon",
                "element": "Force",
                "faction": "Goblin",
                "role": "Frontline",
                "description": "A loud-mouthed scrapper whose banner drives nearby goblins into a frenzy.",
                "base_hp": 1200,
                "base_atk": 110,
                "base_def": 50,
                "base_matk": 25,
                "base_mdef": 40,
                "base_speed": 110,
                "growth_hp": 95,
                "growth_atk": 8,
                "growth_def": 4,
                "growth_matk": 1,
                "growth_mdef": 3,
                "growth_speed": 4,
            },
            {
                "name": "Goblin Powder Alchemist",
                "rarity": "Uncommon",
                "element": "Fire",
                "faction": "Goblin",
                "role": "Backline",
                "description": "An unstable goblin chemist who turns fallen allies into volatile opportunities.",
                "base_hp": 900,
                "base_atk": 45,
                "base_def": 35,
                "base_matk": 130,
                "base_mdef": 60,
                "base_speed": 115,
                "growth_hp": 70,
                "growth_atk": 2,
                "growth_def": 2,
                "growth_matk": 10,
                "growth_mdef": 4,
                "growth_speed": 4,
            },
            {
                "name": "Goblin Traprunner",
                "rarity": "Uncommon",
                "element": "Tech",
                "faction": "Goblin",
                "role": "Frontline",
                "description": "A hyperactive saboteur who turns speed and misdirection into battlefield control.",
                "base_hp": 1000,
                "base_atk": 80,
                "base_def": 40,
                "base_matk": 30,
                "base_mdef": 45,
                "base_speed": 130,
                "growth_hp": 80,
                "growth_atk": 6,
                "growth_def": 3,
                "growth_matk": 1,
                "growth_mdef": 3,
                "growth_speed": 6,
            },
            {
                "name": "Goblin Warcaller",
                "rarity": "Rare",
                "element": "Force",
                "faction": "Goblin",
                "role": "Backline",
                "description": "A vicious instigator whose battle cries turn goblin mobs into a frenzy of blades.",
                "base_hp": 1000,
                "base_atk": 55,
                "base_def": 45,
                "base_matk": 95,
                "base_mdef": 70,
                "base_speed": 105,
                "growth_hp": 80,
                "growth_atk": 3,
                "growth_def": 3,
                "growth_matk": 7,
                "growth_mdef": 5,
                "growth_speed": 3,
            },
            {
                "name": "Goblin Scrap Lord",
                "rarity": "Rare",
                "element": "Fire",
                "faction": "Goblin",
                "role": "Frontline",
                "description": "A brutal enforcer who grows deadlier with every goblin that falls in battle.",
                "base_hp": 1450,
                "base_atk": 125,
                "base_def": 55,
                "base_matk": 30,
                "base_mdef": 50,
                "base_speed": 100,
                "growth_hp": 110,
                "growth_atk": 9,
                "growth_def": 4,
                "growth_matk": 1,
                "growth_mdef": 4,
                "growth_speed": 3,
            },
            {
                "name": "Mad Bombardier Prime",
                "rarity": "Epic",
                "element": "Fire",
                "faction": "Goblin",
                "role": "Backline",
                "description": "A deranged explosives savant who turns goblins into ammunition for devastating strikes.",
                "base_hp": 1050,
                "base_atk": 65,
                "base_def": 45,
                "base_matk": 160,
                "base_mdef": 80,
                "base_speed": 110,
                "growth_hp": 85,
                "growth_atk": 3,
                "growth_def": 3,
                "growth_matk": 14,
                "growth_mdef": 6,
                "growth_speed": 4,
            },
            {
                "name": "Swarm Overboss",
                "rarity": "Epic",
                "element": "Force",
                "faction": "Goblin",
                "role": "Frontline",
                "description": "A tyrannical brute whose presence forces goblins into an even deadlier mob.",
                "base_hp": 1850,
                "base_atk": 135,
                "base_def": 70,
                "base_matk": 40,
                "base_mdef": 65,
                "base_speed": 95,
                "growth_hp": 140,
                "growth_atk": 9,
                "growth_def": 5,
                "growth_matk": 2,
                "growth_mdef": 5,
                "growth_speed": 2,
            },
            {
                "name": "The Great Scrap King",
                "rarity": "Legendary",
                "element": "Fire",
                "faction": "Goblin",
                "role": "Frontline",
                "description": "A deranged monarch who turns goblin deaths into raw momentum and catastrophic victory.",
                "base_hp": 2000,
                "base_atk": 150,
                "base_def": 70,
                "base_matk": 60,
                "base_mdef": 65,
                "base_speed": 105,
                "growth_hp": 150,
                "growth_atk": 10,
                "growth_def": 4,
                "growth_matk": 3,
                "growth_mdef": 4,
                "growth_speed": 3,
            },

            # =========================
            # WILD – COMMON EXAMPLE
            # =========================
            {
                "name": "Fungal Sporeling",
                "rarity": "Common",
                "element": "Spirit",
                "faction": "Wild",
                "role": "Frontline",
                "description": "A toxic pest that spreads decay.",
                "base_hp": 1200,
                "base_atk": 80,
                "base_def": 50,
                "base_matk": 90,
                "base_mdef": 50,
                "base_speed": 100,
                "growth_hp": 100,
                "growth_atk": 5,
                "growth_def": 5,
                "growth_matk": 5,
                "growth_mdef": 5,
                "growth_speed": 2,
            },
        ]

        for hero_data in data:
            obj, created = HeroBase.objects.update_or_create(
                name=hero_data["name"],
                defaults=hero_data,
            )
            action = "Created" if created else "Updated"
            self.stdout.write(f"{action} hero: {obj.name}")
