# Generated by Django 6.0 on 2025-12-21 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rarity', models.CharField(choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Epic', 'Epic'), ('Legendary', 'Legendary')], max_length=20)),
                ('faction', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('base_hp', models.IntegerField()),
                ('base_atk', models.IntegerField()),
                ('base_def', models.IntegerField()),
                ('base_matk', models.IntegerField()),
                ('base_mdef', models.IntegerField()),
                ('base_speed', models.IntegerField()),
                ('growth_hp', models.IntegerField()),
                ('growth_atk', models.IntegerField()),
                ('growth_def', models.IntegerField()),
                ('growth_matk', models.IntegerField()),
                ('growth_mdef', models.IntegerField()),
                ('growth_speed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HeroInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('xp', models.IntegerField(default=0)),
                ('hero_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FO_game.herobase')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heroes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.BigIntegerField(default=200000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
