# Generated by Django 6.0 on 2025-12-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FO_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobase',
            name='element',
            field=models.CharField(choices=[('Magic', 'Magic'), ('Spirit', 'Spirit'), ('Force', 'Force'), ('Void', 'Void'), ('Tech', 'Tech'), ('Fire', 'Fire')], default='fire', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='herobase',
            name='faction',
            field=models.CharField(choices=[('Undead', 'Undead'), ('Goblin', 'Goblin'), ('Wild', 'Wild')], max_length=20),
        ),
    ]
