# Generated by Django 6.0 on 2025-12-24 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FO_game', '0002_herobase_element_alter_herobase_faction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True)),
                ('image', models.ImageField(upload_to='game_assets/')),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='herobase',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_backgrounds', to='FO_game.assetimage'),
        ),
        migrations.AddField(
            model_name='herobase',
            name='portrait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_portraits', to='FO_game.assetimage'),
        ),
        migrations.CreateModel(
            name='SpriteSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True)),
                ('frame_w', models.IntegerField(default=48)),
                ('frame_h', models.IntegerField(default=48)),
                ('directions', models.CharField(default='NW,NE,SE,SW', max_length=40)),
                ('frames_per_direction', models.IntegerField(default=4)),
                ('fps', models.IntegerField(default=8)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='FO_game.assetimage')),
            ],
        ),
        migrations.CreateModel(
            name='AbilityBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('basic', 'Basic'), ('active', 'Active'), ('passive', 'Passive')], default='active', max_length=20)),
                ('targeting', models.CharField(choices=[('single_enemy', 'Single Enemy'), ('all_enemies', 'All Enemies'), ('single_ally', 'Single Ally'), ('all_allies', 'All Allies'), ('self', 'Self')], default='single_enemy', max_length=30)),
                ('skill_power', models.FloatField(default=1.0)),
                ('cooldown_ticks', models.IntegerField(default=0)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ability_icons', to='FO_game.assetimage')),
                ('anim_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abilities', to='FO_game.spritesheet')),
            ],
        ),
        migrations.AddField(
            model_name='herobase',
            name='base_idle_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_idle_sheets', to='FO_game.spritesheet'),
        ),
        migrations.CreateModel(
            name='HeroAbilityLoadout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
                ('unlock_level', models.IntegerField(default=1)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipped_on', to='FO_game.abilitybase')),
                ('hero_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ability_loadout', to='FO_game.herobase')),
            ],
            options={
                'ordering': ['slot'],
                'unique_together': {('hero_base', 'slot')},
            },
        ),
    ]
